name: Build and deploy Node.js app to Azure Web App - mean-stack

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Step 3: Install dependencies for frontend
      - name: npm install for frontend
        run: npm install
        working-directory: frontend

      # Step 4: Build the frontend application
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
        working-directory: frontend

      # Step 5: Debugging build directory (list the contents)
      - name: Debug build directory
        run: ls -R frontend

      # Step 6: Upload the built frontend files as an artifact
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: frontend/dist/frontend  # Update this path based on your local structure

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # This is required for requesting the JWT

    steps:
      # Step 1: Download artifact from build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Step 2: Login to Azure using Service Principal credentials
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_82C2DB72C45243E78DAA8EDC496A4B20 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3C93E27C406E41B983D1650701C9B301 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A21F632E96454781876AE69EC74B5C03 }}

      # Step 3: Deploy the built artifact to Azure Web App
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'mean-stack'          # Azure App Service name
          slot-name: 'Production'        # Deployment slot (can be 'Production' or another slot)
          package: './frontend/dist/frontend'  # Path to the built app (updated for your directory)
